// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmW3qS4LyuwRmRJwS5PANh5L-EogUOq7Y',
    appId: '1:727272198529:web:2688ed371307c5088b5880',
    messagingSenderId: '727272198529',
    projectId: 'flexi-space-528b1',
    authDomain: 'flexi-space-528b1.firebaseapp.com',
    storageBucket: 'flexi-space-528b1.firebasestorage.app',
    measurementId: 'G-E539Y0LNB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUpcAbW3HktbVluH1SEmXd7IjifNFOk68',
    appId: '1:727272198529:android:afd1e7815187af198b5880',
    messagingSenderId: '727272198529',
    projectId: 'flexi-space-528b1',
    storageBucket: 'flexi-space-528b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABwBS8F0KEkoCx8Fn6RlVm54RulmqgebA',
    appId: '1:727272198529:ios:cd61ae4f3193abdf8b5880',
    messagingSenderId: '727272198529',
    projectId: 'flexi-space-528b1',
    storageBucket: 'flexi-space-528b1.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABwBS8F0KEkoCx8Fn6RlVm54RulmqgebA',
    appId: '1:727272198529:ios:cd61ae4f3193abdf8b5880',
    messagingSenderId: '727272198529',
    projectId: 'flexi-space-528b1',
    storageBucket: 'flexi-space-528b1.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmW3qS4LyuwRmRJwS5PANh5L-EogUOq7Y',
    appId: '1:727272198529:web:6ad674a409a0b78e8b5880',
    messagingSenderId: '727272198529',
    projectId: 'flexi-space-528b1',
    authDomain: 'flexi-space-528b1.firebaseapp.com',
    storageBucket: 'flexi-space-528b1.firebasestorage.app',
    measurementId: 'G-DFNBG5P48G',
  );
}
